version: '0.0.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: gagan
      MYSQL_PASSWORD: gagan
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: gagan
      SPRING_DATASOURCE_PASSWORD: gagan

  react-app:
    build:
      context: ../docker-app
    ports:
      - "3000:3000"
    depends_on:
      - springboot-app

volumes:
  mysql-data: