name : spring GHA
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version : '22'
          distribution : 'temurin'
      - name : Build
        run : mvn clean install
      - name : Run tests
        run : mvn test
        if: ${{contains(github.event.head_commit.message , 'test commit ')}}
      - name: Check results
        run:
          echo “event = ${{github.event_name}}”
          echo “Repository = ${{github.repository}}”
          echo “JOB ID = ${{github.job}}”
          echo “RUN ID = ${{github.run_id}}”
          echo “User = ${{github.actor}}”
      - name: Upload jar to Github
        if: ${{contains(github.actor,'gaganvaishnav111')}}
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar